print("Hi classmates!")
print("I wasn't sure what to post so I whipped up something random")
FirstName = input("What's you're first name? ")
lastname = input ("What's your last name? ")
print("Hey there,")
print(FirstName.title())
print(lastname.title())
print("It's been a pleasure learning Python with you!")
print("That's it. An easy peasy short code. Have a great rest of your day!")